### ISSUE TITLE
Vaadin 10 Button - HTML API Page seems broken or no content

### ISSUE THREAD

**Issue by fufex79** [vaadin/vaadin.com#46] opened 2018-06-21 12:15 UTC
HTMP API Page seems broken or no content
https://vaadin.com/components/vaadin-button/html-api

**Comment by Haprog** [comment] 2018-06-21 12:22
Thank you for the issue report. The page is actually functional with the right content, but we are aware that there is a UX issue with this page.

The issue is that it's not visually obvious that there is a link on the page that you need to click to see the API for the `<vaadin-button>` element.

The text [`<vaadin-button> (Vaadin.ButtonElement)`](https://vaadin.com/components/vaadin-button/html-api/elements/Vaadin.ButtonElement) on the page is actually a link which opens the API for that element.

This makes sense in case of other components that actually contain multiple custom elements so you first see a list of the elements and then go deeper, but in these cases when there is only one element we should change the behaviour to directly show the details of that element instead showing a list with only one item that links to the element API.

Also the link color should probably be changed for better UX.

**Comment by fufex79** [comment] 2018-06-21 12:43
Oh wow, thank you. Yeah, the UX on this page could be improved :)

**Comment by mickoyuh** [comment] 2018-07-02 10:52
Closing as the original issue was fixed. Improvement idea recorded.

**Closed as completed by mickoyuh** 2018-07-02 10:52 UTC
